Repository rtdip/core, pull requests merged in 2023-08, with the labels that each got.

#408 Add metadata Step to the Time Weighted Average Function, Unit test and Documentation updates.
  src/api/v1/models.py
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/time_weighted_average.py
  tests/sdk/python/rtdip_sdk/queries/test_time_weighted_average.py
Labels: queries

#412 Add option to remove nanoseconds from Process Control Data Model writes on timestamp
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
Labels: ingestion framework

#415 Minor adjustments for Pipeline functions
  .github/workflows/sonarcloud.yml
  environment.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/azure_key_vault.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/pipeline_components.py
  tests/sdk/python/rtdip_sdk/pipelines/secrets/test_azure_key_vault_secrets.py
Labels: ingestion framework

#419 Add Trigger "AvailableNow" Logic for Streams
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/autoloader.py
  tests/sdk/python/rtdip_sdk/pipelines/deploy/test_databricks_deploy.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kafka.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_autoloader.py
Labels: ingestion framework

#420 Add default pip install in getting started docs
  docs/getting-started/installation.md
Labels: documentation

#421 Update for casting of data types on SSIP Stream
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/ssip_pi_binary_json_to_pcdm.py
Labels: ingestion framework

#423 Add Linear Interpolation to Interpolate Function with updated Docs and Unit Tests
  docs/sdk/code-reference/query/interpolate.md
  docs/sdk/queries/databricks/databricks-sql.md
  src/api/v1/models.py
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_resample.py
Labels: queries

#424 Pandas Package upgrade
  environment.yml
  setup.py
  src/api/requirements.txt
  src/sdk/python/rtdip_sdk/_sdk_utils/pandas.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/base_iso.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/pandas_to_pyspark.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_miso_daily_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_miso_historical_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_pjm_daily_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_pjm_historical_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_ssip_pi_binary_file_to_pcdm.py
Labels: ingestion framework

#435 Meter Forecasting Energy Domain Specific Preamble
  docs/domains/smart_meter/data_model.md
  docs/domains/smart_meter/overview.md
  docs/domains/weather/overview.md
  mkdocs.yml
Labels: documentation

#436 Updates for Mkdocs Blogs
  .vscode/settings.json
  docs/api/overview.md
  docs/api/rest_apis.md
  docs/blog/.authors.yml
  docs/blog/images/framework.png
  docs/blog/index.md
  docs/blog/overview.md
  docs/blog/posts/delta_and_rtdip.md
  docs/blog/posts/rtdip_generative_ai_sql_agent.md
  docs/blog/posts/rtdip_ingestion_pipelines.md
  docs/roadmap/roadmap-overview.md
  docs/sdk/pipelines/components.md
  docs/sdk/pipelines/framework.md
  environment.yml
  mkdocs.yml
Labels: documentation

#438 Additional fields for Eventhub Kafka component
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka_eventhub.py
Labels: ingestion framework

#439 Spark Connector remove stopping Spark Session
  src/sdk/python/rtdip_sdk/connectors/grpc/spark_connector.py
Labels: queries

#442 Created Circular Average and Circular Standard Deviation Query Functions with Unit Tests and Docs
  docs/sdk/code-reference/query/circular-average.md
  docs/sdk/code-reference/query/circular-standard-deviation.md
  docs/sdk/code-reference/query/interpolation-at-time.md
  docs/sdk/examples/query/Circular-Average.md
  docs/sdk/examples/query/Circular-Standard-Deviation.md
  docs/sdk/queries/functions.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_average.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_standard_deviation.py
  tests/sdk/python/rtdip_sdk/queries/test_circular_average.py
  tests/sdk/python/rtdip_sdk/queries/test_circular_standard_deviation.py
Labels: queries

#444 Query Builder
  docs/domains/smart_meter/data_model.md
  docs/domains/smart_meter/overview.md
  docs/domains/weather/overview.md
  docs/sdk/code-reference/query/query_builder.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/queries/__init__.py
  src/sdk/python/rtdip_sdk/queries/query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/time_weighted_average.py
  tests/docs/test_mkdocs_build.py
  tests/sdk/python/rtdip_sdk/queries/test_circular_average.py
  tests/sdk/python/rtdip_sdk/queries/test_circular_standard_deviation.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolation_at_time.py
  tests/sdk/python/rtdip_sdk/queries/test_metadata.py
  tests/sdk/python/rtdip_sdk/queries/test_query_builder.py
  tests/sdk/python/rtdip_sdk/queries/test_raw.py
  tests/sdk/python/rtdip_sdk/queries/test_resample.py
  tests/sdk/python/rtdip_sdk/queries/test_time_weighted_average.py
Labels: queries

#449 Update mkdocs packages
  environment.yml
  setup.py
  src/api/requirements.txt
Labels: documentation

#451 Pandas version updates
  environment.yml
  setup.py
  src/sdk/python/rtdip_sdk/_sdk_utils/pandas.py
Labels: ingestion framework

#456 Update to release.yml for Auto Generated Release Notes
  .github/release.yml
Labels: release

#460 Update for Query Builder
  setup.py
  src/sdk/python/rtdip_sdk/connectors/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
Labels: queries

#465 Query Optimisation for Resample and Interpolate Functions
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_resample.py
Labels: queries
