Repository rtdip/core, pull requests merged in 2023-09, with the labels that each got.

#469 changes to HW pipeline, python delta and eventhub destination
  src/sdk/python/rtdip_sdk/pipelines/destinations/python/delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/pcdm_to_honeywell_apm.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_pcdm_to_honeywell_apm.py
Labels: bug

#476 add EdgeX Eventhub to delta sample to docs
  docs/sdk/examples/pipelines/deploy/EdgeX-Eventhub-to-Delta.md
  mkdocs.yml
Labels: documentation

#477 Kafka Eventhub Destination
  docs/sdk/code-reference/pipelines/destinations/spark/kafka_eventhub.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kafka_eventhub.py
Labels: enhancement

#479 add unit tests to kafka eventhub source
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kafka_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kafka_eventhub.py
Labels: unit tests

#481 MQTT Json to PCDM Transformer
  docs/sdk/code-reference/pipelines/transformers/spark/mqtt_json_to_pcdm.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/obc_field_mappings.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/mqtt_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_mqtt_json_to_pcdm.py
Labels: pipelines

#486 Kafka Eventhub Destination fixes
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/pcdm_to_honeywell_apm.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kafka_eventhub.py
Labels: documentation

#490 v0.7.8
  src/api/v1/common.py
  src/api/v1/interpolate.py
  src/api/v1/interpolation_at_time.py
  src/api/v1/models.py
  src/api/v1/resample.py
  src/api/v1/time_weighted_average.py
  src/sdk/python/rtdip_sdk/connectors/odbc/db_sql_connector.py
  src/sdk/python/rtdip_sdk/connectors/odbc/pyodbc_sql_connector.py
  src/sdk/python/rtdip_sdk/connectors/odbc/turbodbc_sql_connector.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/pcdm_to_honeywell_apm.py
  src/sdk/python/rtdip_sdk/queries/metadata.py
  src/sdk/python/rtdip_sdk/queries/query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_average.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_standard_deviation.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolate.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolation_at_time.py
  src/sdk/python/rtdip_sdk/queries/time_series/raw.py
  src/sdk/python/rtdip_sdk/queries/time_series/resample.py
  src/sdk/python/rtdip_sdk/queries/time_series/time_weighted_average.py
  tests/sdk/python/rtdip_sdk/connectors/odbc/test_db_sql_connector.py
  tests/sdk/python/rtdip_sdk/connectors/odbc/test_pyodbc_sql_connector.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kafka_eventhub.py
  tests/sdk/python/rtdip_sdk/queries/test_circular_average.py
  tests/sdk/python/rtdip_sdk/queries/test_circular_standard_deviation.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolation_at_time.py
  tests/sdk/python/rtdip_sdk/queries/test_metadata.py
  tests/sdk/python/rtdip_sdk/queries/test_raw.py
  tests/sdk/python/rtdip_sdk/queries/test_resample.py
  tests/sdk/python/rtdip_sdk/queries/test_time_weighted_average.py
Labels: release

#491 Add offset and limits to Query Builder
  src/sdk/python/rtdip_sdk/queries/query_builder.py
Labels: queries

#492 Add Offsets, Limits and Databricks SQL Headers to APIs
  environment.yml
  setup.py
  src/api/requirements.txt
  src/api/v1/common.py
  src/api/v1/interpolate.py
  src/api/v1/interpolation_at_time.py
  src/api/v1/metadata.py
  src/api/v1/models.py
  src/api/v1/raw.py
  src/api/v1/resample.py
  src/api/v1/time_weighted_average.py
  src/sdk/python/rtdip_sdk/queries/metadata.py
  src/sdk/python/rtdip_sdk/queries/query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_average.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_standard_deviation.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolate.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolation_at_time.py
  src/sdk/python/rtdip_sdk/queries/time_series/raw.py
  src/sdk/python/rtdip_sdk/queries/time_series/resample.py
  src/sdk/python/rtdip_sdk/queries/time_series/time_weighted_average.py
  tests/api/v1/api_test_objects.py
Labels: queries

#493 v0.7.9
  environment.yml
  setup.py
  src/api/requirements.txt
  src/api/v1/common.py
  src/api/v1/interpolate.py
  src/api/v1/interpolation_at_time.py
  src/api/v1/metadata.py
  src/api/v1/models.py
  src/api/v1/raw.py
  src/api/v1/resample.py
  src/api/v1/time_weighted_average.py
  src/sdk/python/rtdip_sdk/queries/metadata.py
  src/sdk/python/rtdip_sdk/queries/query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_average.py
  src/sdk/python/rtdip_sdk/queries/time_series/circular_standard_deviation.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolate.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolation_at_time.py
  src/sdk/python/rtdip_sdk/queries/time_series/raw.py
  src/sdk/python/rtdip_sdk/queries/time_series/resample.py
  src/sdk/python/rtdip_sdk/queries/time_series/time_weighted_average.py
  tests/api/v1/api_test_objects.py
Labels: release

#494 Fix for Linear Interpolation Query
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
Labels: bug

#495 v0.7.10
  src/sdk/python/rtdip_sdk/data_models/meters/ami_meter.py
  src/sdk/python/rtdip_sdk/data_models/meters/utils/CreateMetaDataObject.py
  src/sdk/python/rtdip_sdk/data_models/meters/utils/CreateUsageObject.py
  src/sdk/python/rtdip_sdk/data_models/storage_objects/storage_objects_utils.py
  src/sdk/python/rtdip_sdk/data_models/timeseries.py
  src/sdk/python/rtdip_sdk/data_models/utils/CreateTimeSeriesObject.py
  src/sdk/python/rtdip_sdk/data_models/utils/timeseries_utils.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/base_raw_to_mdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/miso_to_mdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/pjm_to_mdm.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_copy_utility.py
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  tests/sdk/python/rtdip_sdk/data_models/meters/test_timeseries.py
  tests/sdk/python/rtdip_sdk/data_models/storage_objects/test_storage_objects_utils.py
  tests/sdk/python/rtdip_sdk/data_models/test_timeseries.py
  tests/sdk/python/rtdip_sdk/data_models/transformers/test_transformers.py
  tests/sdk/python/rtdip_sdk/data_models/utils/test_utils.py
  tests/sdk/python/rtdip_sdk/data_models/weather/test_weather_objects.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_miso_to_mdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_pjm_to_mdm.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/aws/test_s3_copy_utility.py
Labels: release

#497 Updates for MQTT from Open X
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/mqtt_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_mqtt_json_to_pcdm.py
Labels: pipelines

#499 Fix bug on MQTT Tranformer and rename to SEM
  docs/sdk/code-reference/pipelines/transformers/spark/mqtt_json_to_pcdm.md
  docs/sdk/code-reference/pipelines/transformers/spark/sem_json_to_pcdm.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/sem_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_sem_json_to_pcdm.py
Labels: bug

#500 Additional parameters for delta destination
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta.py
Labels: pipelines

#501 Additional wait logic for streaming destinations
  .github/workflows/test.yml
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_rest_api.py
Labels: pipelines

#503 Update SEM Transformer Column and Datatype Mappings
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/obc_field_mappings.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/sem_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_sem_json_to_pcdm.py
Labels: bug

#505 HW APM schema change
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/honeywell_apm_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_honeywell_apm_to_pcdm.py
Labels: bug

#507 Update Mapping DataTypes
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/obc_field_mappings.py
Labels: bug

#508 Update sdk packages
  environment.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta_sharing.py
Labels: pipelines

#511 Add checkpoint logic to PCDM Delta stream writes
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
Labels: pipelines

#512 PCDM Delta Latest Values to Delta
  docs/sdk/code-reference/pipelines/destinations/spark/pcdm_latest_to_delta.md
  docs/sdk/code-reference/pipelines/destinations/spark/pcdm_to_delta.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_latest_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_latest_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_to_delta.py
Labels: pipelines

#513 PCDM Latest include additional Update logic
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_latest_to_delta.py
Labels: pipelines

#514 Add support for Spark 3.5.0
  .github/workflows/test.yml
  docs/blog/.authors.yml
  environment.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_latest_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_latest_to_delta.py
Labels: pipelines

#515 v0.7.11
  .github/workflows/test.yml
  docs/blog/.authors.yml
  docs/sdk/code-reference/pipelines/destinations/spark/pcdm_latest_to_delta.md
  docs/sdk/code-reference/pipelines/destinations/spark/pcdm_to_delta.md
  docs/sdk/code-reference/pipelines/transformers/spark/mqtt_json_to_pcdm.md
  docs/sdk/code-reference/pipelines/transformers/spark/sem_json_to_pcdm.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/obc_field_mappings.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_latest_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/honeywell_apm_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/sem_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_latest_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_rest_api.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta_sharing.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_honeywell_apm_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_mqtt_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_sem_json_to_pcdm.py
Labels: release
