Repository rtdip/core, pull requests merged in 2023-05, with the labels that each got.

#208 fix unit tests for twa api
  tests/sdk/python/rtdip_sdk/functions/test_time_weighted_average.py
Labels: enhancement

#211 Performance Updates for Turbodbc and Databricks SQL Connector
  docs/api/deployment/azure.md
  environment.yml
  setup.py
  src/api/Dockerfile
  src/api/requirements.txt
  src/api/v1/common.py
  src/api/v1/models.py
  src/sdk/python/rtdip_sdk/functions/time_weighted_average.py
  src/sdk/python/rtdip_sdk/odbc/db_sql_connector.py
  src/sdk/python/rtdip_sdk/odbc/turbodbc_sql_connector.py
  tests/docs/test_macros.py
  tests/sdk/python/rtdip_sdk/functions/test_interpolate.py
  tests/sdk/python/rtdip_sdk/functions/test_metadata.py
  tests/sdk/python/rtdip_sdk/functions/test_raw.py
  tests/sdk/python/rtdip_sdk/functions/test_resample.py
  tests/sdk/python/rtdip_sdk/functions/test_time_weighted_average.py
  tests/sdk/python/rtdip_sdk/odbc/test_db_sql_connector.py
  tests/sdk/python/rtdip_sdk/odbc/test_turbodbc_sql_connector.py
Labels: queries

#212 Add Arrow support for Turbodbc
  src/api/Dockerfile
Labels: queries

#213 Turbodbc Performance Updates
  src/api/Dockerfile
  src/sdk/python/rtdip_sdk/odbc/turbodbc_sql_connector.py
Labels: queries

#214 Update pyarrow install for Turbodbc
  src/api/Dockerfile
Labels: queries

#220 Delta Merge Destination Component
  docs/sdk/code-reference/pipelines/destinations/spark/delta_merge.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta_merge.py
Labels: ingestion framework

#221 Fledge transformer component
  docs/sdk/code-reference/pipelines/transformers/spark/fledge_json_to_pcdm.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/api/v1/interpolate.py
  src/api/v1/metadata.py
  src/api/v1/raw.py
  src/api/v1/resample.py
  src/api/v1/time_weighted_average.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/fledge_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_fledge_json_to_pcdm.py
Labels: ingestion framework

#227 Hashicorp Vault Secret Component
  docs/sdk/code-reference/pipelines/secrets/hashicorp_vault.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/hashicorp_vault.py
  tests/sdk/python/rtdip_sdk/pipelines/secrets/test_hashicorp_secrets.py
Labels: ingestion framework

#232 Spark ADLS Gen2 Service Principal Connect Utility
  docs/sdk/code-reference/pipelines/utilities/spark/adls_gen2_spn_connect.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/adls_gen2_spn_connect.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_adls_gen2_spn_connect.py
Labels: ingestion framework

#230 Azure Key Vault Secret Component
  docs/sdk/code-reference/pipelines/secrets/azure_key_vault.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/azure_key_vault.py
  tests/sdk/python/rtdip_sdk/pipelines/secrets/test_azure_key_vault_secrets.py
Labels: ingestion framework

#233 SSIP PI Transformer Components
  .vscode/settings.json
  docs/sdk/code-reference/pipelines/transformers/spark/fledge_json_to_pcdm.md
  docs/sdk/code-reference/pipelines/transformers/spark/opc_publisher_json_to_pcdm.md
  docs/sdk/code-reference/pipelines/transformers/spark/ssip_pi_binary_file_to_pcdm.md
  docs/sdk/code-reference/pipelines/transformers/spark/ssip_pi_binary_json_to_pcdm.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/fledge_json_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/opc_publisher_json_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/ssip_pi_binary_file_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/ssip_pi_binary_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark_configuration_constants.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_ssip_pi_binary_file_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_ssip_pi_binary_json_to_pcdm.py
Labels: ingestion framework

#234 Process Control Data Model
  .vscode/settings.json
  docs/domains/process_control/data_model.md
  docs/domains/process_control/images/iot_hub.png
  docs/domains/process_control/images/kafka-logo-wide.png
  docs/domains/process_control/images/mqtt.png
  docs/domains/process_control/overview.md
  mkdocs.yml
Labels: documentation

#238 Delta Batch Updates
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_to_delta.py
Labels: ingestion framework

#236 added timezone to docs
  docs/sdk/code-reference/query/interpolate.md
  docs/sdk/code-reference/query/raw.md
  docs/sdk/code-reference/query/resample.md
  docs/sdk/code-reference/query/time-weighted-average.md
  src/sdk/python/rtdip_sdk/functions/interpolate.py
  src/sdk/python/rtdip_sdk/functions/raw.py
  src/sdk/python/rtdip_sdk/functions/resample.py
  src/sdk/python/rtdip_sdk/functions/time_weighted_average.py
Labels: documentation

#243 Updates for AMI Meter Classes
  src/sdk/python/rtdip_sdk/data_models/meters/ami_meters.py
  src/sdk/python/rtdip_sdk/data_models/transformers/london_smart_meter_transformer_2_usage.py
  src/sdk/python/rtdip_sdk/data_models/weather/weather_models.py
Labels: data model

#251 Support 3.3.* Pyspark Versions
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
  environment.yml
  setup.py
  src/sdk/python/rtdip_sdk/_sdk_utils/__init__.py
  src/sdk/python/rtdip_sdk/_sdk_utils/compare_versions.py
  src/sdk/python/rtdip_sdk/functions/metadata.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/models.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/execute/job.py
  src/sdk/python/rtdip_sdk/pipelines/execute/models.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_bucket_policy.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/configuration.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_create.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_optimize.py
  tests/sdk/python/rtdip_sdk/_sdk_utils/__init__.py
  tests/sdk/python/rtdip_sdk/_sdk_utils/test_compare_versions.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta_merge.py
Labels: ingestion framework

#252 Fix setup.py package
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
  setup.py
Labels: bug

#261 Databricks System Parameter Index Change
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/rtdip/tasks/pipeline_task.py
Labels: bug

#271 EdgeX Transformer
  docs/domains/process_control/data_model.md
  docs/sdk/code-reference/pipelines/transformers/spark/edgex_json_to_pcdm.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/edgex_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_edgex_json_to_pcdm.py
Labels: ingestion framework

#274 Add Partition Pruning to non broadcast join PCDM Merge
  .vscode/settings.json
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
Labels: ingestion framework

#291 Fix mkdocs colour bug
  docs/assets/extra.css
  mkdocs.yml
Labels: bug, documentation

#296 Add Filter Parameter and TagName field mapping for OPC Publisher Transformer
  .vscode/settings.json
  docs/domains/process_control/data_model.md
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/opc_publisher_json_to_pcdm.py
Labels: ingestion framework

#294 Weather Domain and Data Model
  docs/domains/weather/data_model.md
  docs/domains/weather/overview.md
  mkdocs.yml
Labels: data model

#303 Upgrade FastAPI Package
  src/api/requirements.txt
Labels: Mend: dependency security vulnerability
