Repository rtdip/core, pull requests merged in 2023-07, with the labels that each got.

#349 Spark Session Utility Component
  .vscode/settings.json
  docs/sdk/code-reference/pipelines/utilities/spark/session.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  src/sdk/python/rtdip_sdk/_sdk_utils/compare_versions.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/ssip_pi_binary_file_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/session.py
  tests/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark_configuration_constants.py
Labels: ingestion framework

#352 Change Imports for SSIP UDF to execute properly
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/azure_key_vault.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/hashicorp_vault.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/autoloader.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/delta_sharing.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iot_hub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/ssip_pi_binary_file_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_bucket_policy.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/adls_gen2_acl.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/adls_gen2_spn_connect.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_create.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_optimize.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_vacuum.py
Labels: bug

#353 Updates for Default Packages Logic
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/converters/pipeline_job_json.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
  src/sdk/python/rtdip_sdk/pipelines/execute/models.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/azure_key_vault.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/hashicorp_vault.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/autoloader.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/delta.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/delta_sharing.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iot_hub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/ssip_pi_binary_file_to_pcdm.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_bucket_policy.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/adls_gen2_acl.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_create.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_optimize.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_vacuum.py
  tests/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark_configuration_constants.py
Labels: bug

#355 EVM destination component unit tests
  docs/sdk/pipelines/components.md
  src/sdk/python/rtdip_sdk/pipelines/destinations/blockchain/evm.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/blockchain/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/blockchain/test_evm.py
Labels: unit tests

#327 Weather Data Connector - Feature/00137
  docs/sdk/code-reference/pipelines/sources/spark/weather/base_weather.md
  docs/sdk/code-reference/pipelines/sources/spark/weather/weather_forecast_api_v1.md
  docs/sdk/code-reference/pipelines/sources/spark/weather/weather_forecast_api_v1_multi.md
  docs/sdk/code-reference/pipelines/transformers/spark/eventhub.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/weather.py
  src/sdk/python/rtdip_sdk/pipelines/sources/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/base_weather.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/weather_forecast_api_v1.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/weather_forecast_api_v1_multi.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/test_base_weather.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/test_weather_forecast_api_v1.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/test_weather_forecast_api_v1_multi.py
Labels: ingestion framework

#321 Support for Raw data to MDM Transformer class with Implementation for MISO
  docs/sdk/code-reference/pipelines/transformers/spark/base_raw_to_mdm.md
  docs/sdk/code-reference/pipelines/transformers/spark/iso/miso_to_mdm.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/data_models/meters/ami_meters.py
  src/sdk/python/rtdip_sdk/data_models/meters/utils/CreateMetaDataObject.py
  src/sdk/python/rtdip_sdk/data_models/meters/utils/CreateUsageObject.py
  src/sdk/python/rtdip_sdk/data_models/meters/utils/utils.py
  src/sdk/python/rtdip_sdk/data_models/transformers/london_smart_meter_transformer_2_usage.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/iso.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/mdm.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/base_iso.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/miso_daily_load_iso.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/miso_historical_load_iso.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/base_raw_to_mdm.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/miso_to_mdm.py
  tests/sdk/python/rtdip_sdk/data_models/meters/test_timeseries.py
  tests/sdk/python/rtdip_sdk/data_models/meters/utils/test_utils.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_miso_daily_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_miso_historical_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_data/miso_meta/input.csv
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_data/miso_meta/output.json
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_data/miso_usage/input.csv
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_data/miso_usage/output.csv
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_miso_to_mdm.py
Labels: ingestion framework

#358 Fix for unit test runtime performance
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/session.py
  tests/conftest.py
  tests/sdk/python/rtdip_sdk/connectors/grpc/test_spark_connector.py
  tests/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark_configuration_constants.py
  tests/sdk/python/rtdip_sdk/pipelines/deploy/test_databricks_deploy.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta_merge.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kafka.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_rest_api.py
  tests/sdk/python/rtdip_sdk/pipelines/execute/test_spark_job.py
  tests/sdk/python/rtdip_sdk/pipelines/secrets/test_databricks_secrets.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_base_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_miso_daily_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_miso_historical_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_autoloader.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta_sharing.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_iot_hub.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kafka.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/test_base_weather.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/test_weather_forecast_api_v1.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/weather/test_weather_forecast_api_v1_multi.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/iso/test_miso_to_mdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_binary_to_string.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_edgex_opcua_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_fledge_opcua_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_opc_publisher_opcua_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_pandas_to_pyspark.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_pyspark_to_pandas.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_ssip_pi_binary_file_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_ssip_pi_binary_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_adls_gen2_spn_connect.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_configuration.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_delta_table_create.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_delta_table_optimize.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_delta_table_vacuum.py
Labels: bug

#359 Fix for Circular Imports
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/session.py
Labels: bug

#361 Add OpenSSF Tag
  README.md
Labels: documentation

#373 Update packages for API Container
  environment.yml
  src/api/Dockerfile
  src/api/requirements.txt
Labels: bug

#370 Source Component - Energy Domain PJM market
  docs/sdk/code-reference/pipelines/sources/spark/iso/pjm_daily_load_iso.md
  docs/sdk/code-reference/pipelines/sources/spark/iso/pjm_historical_load_iso.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/iso.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/pjm_daily_load_iso.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/pjm_historical_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_pjm_daily_load_iso.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_pjm_historical_load_iso.py
Labels: ingestion framework

#376 Add edgeX to Transformers init
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
Labels: bug, ingestion framework

#377 API Convert NaN to None in JSON Response
  src/api/v1/interpolate.py
  src/api/v1/interpolation_at_time.py
  src/api/v1/metadata.py
  src/api/v1/raw.py
  src/api/v1/resample.py
  src/api/v1/time_weighted_average.py
Labels: queries

#379 Docs for running APIs locally on a Macbook
  src/api/README.md
Labels: documentation

#389 Refactored Resample and Interpolate, removed Jinjasql and updated unit tests
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_resample.py
Labels: enhancement

#392 refactor time weighted average and add unit tests
  src/sdk/python/rtdip_sdk/queries/time_series/_query_builder.py
  src/sdk/python/rtdip_sdk/queries/time_series/interpolation_at_time.py
  src/sdk/python/rtdip_sdk/queries/time_series/time_weighted_average.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/test_interpolation_at_time.py
  tests/sdk/python/rtdip_sdk/queries/test_raw.py
  tests/sdk/python/rtdip_sdk/queries/test_resample.py
  tests/sdk/python/rtdip_sdk/queries/test_time_weighted_average.py
Labels: enhancement

#394 Update Databricks Deploy to use the Databricks SDK
  .gitignore
  docs/sdk/code-reference/pipelines/deploy/databricks.md
  docs/sdk/pipelines/deploy/databricks.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/.gitignore
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/conf/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/conf/deployment.json
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/rtdip/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/rtdip/tasks/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/rtdip/tasks/common.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/rtdip/tasks/pipeline_task.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/dbx/setup.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/models/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/models/databricks.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/pipeline_components.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/session.py
  tests/sdk/python/rtdip_sdk/pipelines/deploy/test_databricks_deploy.py
Labels: ingestion framework

#395 Kafka Eventhub Source
  docs/sdk/code-reference/pipelines/sources/spark/kafka_eventhub.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  setup.py
  src/api/README.md
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/sources/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kafka_eventhub.py
Labels: ingestion framework

#398 doc updates and paramater fix
  docs/sdk/queries/databricks/databricks-sql.md
  docs/sdk/queries/databricks/troubleshooting.md
  docs/sdk/queries/functions.md
  src/api/v1/models.py
Labels: bug
