Repository rtdip/core, pull requests merged in 2023-10, with the labels that each got.

#520 Metadata and Latest Queries - Allow optional tagname_filter
  src/sdk/python/rtdip_sdk/queries/query_builder.py
Labels: queries

#521 Add token to Databricks Workspace Authentication
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
  tests/sdk/python/rtdip_sdk/pipelines/deploy/test_databricks_deploy.py
Labels: pipelines

#522 v0.8.1
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
  src/sdk/python/rtdip_sdk/queries/query_builder.py
  tests/sdk/python/rtdip_sdk/pipelines/deploy/test_databricks_deploy.py
Labels: release

#523 Change Databricks Auth Type from token to pat
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
Labels: pipelines

#524 Support for Spark 3.5.0
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
Labels: pipelines

#528 v0.8.2
  .github/release.yml
  environment.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
Labels: release

#530 Circular avg & circular std deviation APIs
  src/api/v1/__init__.py
  src/api/v1/circular_average.py
  src/api/v1/circular_standard_deviation.py
  src/api/v1/common.py
  src/api/v1/models.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  tests/api/v1/api_test_objects.py
  tests/api/v1/test_api_circular_average.py
  tests/api/v1/test_api_circular_standard_deviation.py
Labels: enhancement

#532 Allow null values in latest API
  environment.yml
  src/api/requirements.txt
  src/api/v1/__init__.py
  src/api/v1/graphql.py
  src/api/v1/models.py
  src/sdk/python/rtdip_sdk/data_models/meters/ami_meter.py
  src/sdk/python/rtdip_sdk/data_models/timeseries.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/models.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
  src/sdk/python/rtdip_sdk/pipelines/execute/models.py
  src/sdk/python/rtdip_sdk/pipelines/secrets/models.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_bucket_policy.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_create.py
  tests/api/v1/api_test_objects.py
  tests/api/v1/test_api_circular_average.py
  tests/api/v1/test_api_circular_standard_deviation.py
  tests/api/v1/test_api_interpolate.py
  tests/api/v1/test_api_interpolation_at_time.py
  tests/api/v1/test_api_latest.py
  tests/api/v1/test_api_metadata.py
  tests/api/v1/test_api_raw.py
  tests/api/v1/test_api_resample.py
  tests/api/v1/test_api_time_weighted_average.py
Labels: bug

#534 Update pydantic version
  setup.py
Labels: bug

#535 v0.8.4
  setup.py
Labels: release

#539 Azure Autoloader Resources Utility Component
  docs/sdk/code-reference/pipelines/utilities/azure/autoloader_resources.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/adls_gen2_acl.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/autoloader_resources.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/azure/test_adls_gen2_acl.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/azure/test_autoloader_resources.py
Labels: pipelines

#540 Fix for setup.py version
  environment.yml
  setup.py
Labels: bug

#542 Updates for Autoloader Resources
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/autoloader_resources.py
Labels: pipelines

#541 v0.8.5
  .devcontainer/devcontainer.json
  .vscode/settings.json
  docs/sdk/code-reference/pipelines/utilities/azure/autoloader_resources.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/adls_gen2_acl.py
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/autoloader_resources.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/azure/test_adls_gen2_acl.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/azure/test_autoloader_resources.py
Labels: release

#545 Support for Spark 3.5.0 and Delta 3.0.0
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
  environment.yml
  setup.py
  src/api/Dockerfile
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
Labels: pipelines

#550 v0.8.6
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
  environment.yml
  setup.py
  src/api/Dockerfile
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta_merge.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_latest_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_to_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_autoloader.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta.py
Labels: release

#554 v0.8.7
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/autoloader_resources.py
  tests/sdk/python/rtdip_sdk/pipelines/utilities/azure/test_autoloader_resources.py
Labels: release
