Repository rtdip/core, pull requests merged in 2023-04, with the labels that each got.

#159 Added Kinesis source and destination
  docs/sdk/code-reference/pipelines/destinations/spark/kinesis.md
  docs/sdk/code-reference/pipelines/sources/spark/kinesis.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/sources/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark_configuration_constants.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kinesis.py
Labels: ingestion framework

#162 OPC UA And Process Control Data Model Transformers
  docs/sdk/code-reference/pipelines/transformers/spark/eventhub.md
  docs/sdk/code-reference/pipelines/transformers/spark/json_to_opcua.md
  docs/sdk/code-reference/pipelines/transformers/spark/opcua_to_process_control_data_model.md
  docs/sdk/pipelines/components.md
  environment.yml
  mkdocs.yml
  setup.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/spark.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/iot_hub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kinesis.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/json_to_opcua.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/opcua_to_process_control_data_model.py
  tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/execute/test_spark_job.py
  tests/sdk/python/rtdip_sdk/pipelines/secrets/test_databricks_secrets.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_autoloader.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_delta_sharing.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_eventhub.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_iot_hub.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kafka.py
  tests/sdk/python/rtdip_sdk/pipelines/sources/spark/test_kinesis.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/__init__.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_json_to_opcua.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_opcua_to_process_control_data_model.py
Labels: ingestion framework

#170 Github Actions Sonarcloud Refactor for forked branches
  .github/workflows/sonarcloud.yml
  .github/workflows/test.yml
Labels: bug

#171 Fix for Test Github Actions Workflow
  .github/workflows/test.yml
Labels: bug

#178 Update Github Workflows for Sonarcloud Scans
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarcloud_reusable.yml
  .github/workflows/test.yml
Labels: bug

#180 Removed repo structure from readme
  README.md
Labels: documentation

#199 Timezone feature for querying functions
  src/sdk/python/rtdip_sdk/functions/_query_builder.py
  src/sdk/python/rtdip_sdk/functions/raw.py
  src/sdk/python/rtdip_sdk/functions/time_weighted_average.py
  tests/api/v1/api_test_objects.py
  tests/sdk/python/rtdip_sdk/functions/test_interpolate.py
  tests/sdk/python/rtdip_sdk/functions/test_raw.py
  tests/sdk/python/rtdip_sdk/functions/test_resample.py
  tests/sdk/python/rtdip_sdk/functions/test_time_weighted_average.py
Labels: enhancement

#202 Documentation Updates
  .devcontainer/devcontainer.json
  .vscode/settings.json
  docs/assets/extra.css
  docs/blog/overview.md
  docs/blog/rtdip_ingestion_pipelines.md
  docs/macros.py
  docs/sdk/code-reference/pipelines/transformers/spark/json_to_opcua.md
  docs/sdk/code-reference/pipelines/transformers/spark/opc_publisher_json_to_opcua.md
  docs/sdk/pipelines/components.md
  docs/sdk/pipelines/framework.md
  docs/sdk/queries/functions.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/opc_publisher_json_to_opcua.py
  tests/docs/test_macros.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_opc_publisher_json_to_opcua.py
Labels: documentation

#206 Package Setup Update for Data Files
  .github/workflows/sonarcloud.yml
  docs/macros.py
  docs/sdk/pipelines/jobs.md
  mkdocs.yml
  setup.py
Labels: ingestion framework
