Repository rtdip/core, pull requests merged in 2024-03, with the labels that each got.

#676 v0.10.0
  docs/sdk/code-reference/pipelines/sources/spark/iso/base_iso.md
  environment.yml
  mkdocs.yml
  setup.py
  src/api/Dockerfile
  src/api/FastAPIApp/__init__.py
  src/api/auth/azuread.py
  src/api/requirements.txt
  src/api/v1/__init__.py
  src/api/v1/circular_average.py
  src/api/v1/circular_standard_deviation.py
  src/api/v1/common.py
  src/api/v1/interpolate.py
  src/api/v1/interpolation_at_time.py
  src/api/v1/latest.py
  src/api/v1/metadata.py
  src/api/v1/models.py
  src/api/v1/raw.py
  src/api/v1/resample.py
  src/api/v1/sql.py
  src/api/v1/summary.py
  src/api/v1/time_weighted_average.py
  src/sdk/python/rtdip_sdk/connectors/cursor_interface.py
  src/sdk/python/rtdip_sdk/connectors/odbc/db_sql_connector.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/databricks.py
  src/sdk/python/rtdip_sdk/pipelines/deploy/interfaces.py
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
  src/sdk/python/rtdip_sdk/queries/sql/sql_query.py
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
  tests/api/auth/test_auth_azuread.py
  tests/api/v1/api_test_objects.py
  tests/api/v1/test_api_circular_average.py
  tests/api/v1/test_api_circular_standard_deviation.py
  tests/api/v1/test_api_interpolate.py
  tests/api/v1/test_api_interpolation_at_time.py
  tests/api/v1/test_api_latest.py
  tests/api/v1/test_api_metadata.py
  tests/api/v1/test_api_raw.py
  tests/api/v1/test_api_resample.py
  tests/api/v1/test_api_sql.py
  tests/api/v1/test_api_summary.py
  tests/api/v1/test_api_time_weighted_average.py
  tests/sdk/python/rtdip_sdk/connectors/odbc/test_db_sql_connector.py
  tests/sdk/python/rtdip_sdk/pipelines/deploy/test_databricks_deploy.py
  tests/sdk/python/rtdip_sdk/queries/sql/test_sql_query.py
  tests/sdk/python/rtdip_sdk/queries/time_series/_test_base.py
  tests/sdk/python/rtdip_sdk/queries/weather/test_latest.py
  tests/sdk/python/rtdip_sdk/queries/weather/test_raw.py
Labels: release

#683 v0.10.1
  src/sdk/python/rtdip_sdk/pipelines/destinations/spark/kafka_eventhub.py
  src/sdk/python/rtdip_sdk/pipelines/sources/spark/kafka_eventhub.py
Labels: release

#684 Add Spark Connect Example to Docs
  docs/sdk/examples/pipelines/deploy/Fledge-SparkConnect-PCDM.md
  mkdocs.yml
Labels: documentation

#701 v0.10.4
  docs/index.md
  environment.yml
  setup.py
  src/api/requirements.txt
  src/api/v1/circular_average.py
  src/api/v1/circular_standard_deviation.py
  src/api/v1/interpolate.py
  src/api/v1/interpolation_at_time.py
  src/api/v1/latest.py
  src/api/v1/metadata.py
  src/api/v1/models.py
  src/api/v1/raw.py
  src/api/v1/resample.py
  src/api/v1/sql.py
  src/api/v1/summary.py
  src/api/v1/time_weighted_average.py
  src/sdk/python/rtdip_sdk/connectors/llm/chatopenai_databricks_connector.py
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
Labels: release

#702 Fix TWA Window EventTime Column
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
Labels: bug

#703 v0.10.5
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
Labels: release

#706 v0.10.6
  src/api/v1/models.py
Labels: release

#708 Mirico Transformer TagName Column Updates
  src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/mirico_field_mappings.py
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/mirico_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_mirico_json_to_pcdm.py
Labels: pipelines

#710 Mirico Tranformer Updates
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/mirico_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_mirico_json_to_pcdm.py
Labels: pipelines

#716 Missing "Good" data fix
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
Labels: queries
