Repository rtdip/core, pull requests merged in 2024-02, with the labels that each got.

#654 Update Mirico Tranformer with an optional tag name field to be appended to TagName column
  src/sdk/python/rtdip_sdk/pipelines/transformers/spark/mirico_json_to_pcdm.py
  tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_mirico_json_to_pcdm.py
Labels: pipelines

#658 Fix Query Performance
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
  tests/sdk/python/rtdip_sdk/queries/_test_utils/sdk_test_objects.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_circular_average.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_circular_standard_deviation.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_interpolate.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_interpolation_at_time.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_latest.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_metadata.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_raw.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_resample.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_summary.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_time_weighted_average.py
Labels: bug

#668 Add Missing Documentation
  docs/sdk/code-reference/pipelines/sources/spark/iso/base_iso.md
  mkdocs.yml
Labels: bug, documentation
