Repository rtdip/core, pull requests merged in 2024-01, with the labels that each got.

#623 Bug Fixes
  setup.py
  tests/sdk/python/rtdip_sdk/connectors/grpc/test_spark_connector.py
  tests/sdk/python/rtdip_sdk/connectors/llm/test_chatopenai_databricks_connector.py
Labels: bug

#632 Added examples to TimeSeriesQueryBuilder
  mkdocs.yml
  src/sdk/python/rtdip_sdk/queries/time_series/time_series_query_builder.py
Labels: documentation

#621 Weather Query Improvement with Forecast Runtime Query
  docs/sdk/code-reference/query/functions/weather/latest.md
  docs/sdk/code-reference/query/functions/weather/raw.md
  docs/sdk/code-reference/query/functions/weather/weather_query_builder.md
  src/sdk/python/rtdip_sdk/queries/weather/_weather_query_builder.py
  src/sdk/python/rtdip_sdk/queries/weather/latest.py
  src/sdk/python/rtdip_sdk/queries/weather/raw.py
  src/sdk/python/rtdip_sdk/queries/weather/weather_query_builder.py
  tests/sdk/python/rtdip_sdk/queries/weather/test_latest.py
  tests/sdk/python/rtdip_sdk/queries/weather/test_raw.py
  tests/sdk/python/rtdip_sdk/queries/weather/test_weather_query_builder.py
Labels: queries

#636 Added components to Pipeline Component list
  docs/sdk/code-reference/pipelines/utilities/aws/s3_copy_utility.md
  docs/sdk/pipelines/components.md
  mkdocs.yml
  src/sdk/python/rtdip_sdk/pipelines/utilities/spark/session.py
Labels: documentation

#640 SDK Documentation Page Restructure
  docs/sdk/images/sdk-logo.png
  docs/sdk/overview.md
  docs/sdk/queries/llm/chatopenai_databricks_connector.md
  mkdocs.yml
Labels: documentation

#643 Measurement Added to Query as Option
  src/sdk/python/rtdip_sdk/queries/weather/_weather_query_builder.py
  src/sdk/python/rtdip_sdk/queries/weather/latest.py
  src/sdk/python/rtdip_sdk/queries/weather/raw.py
  src/sdk/python/rtdip_sdk/queries/weather/weather_query_builder.py
Labels: enhancement, queries

#648 Access ACL is always set and not conditional on default arg
  src/sdk/python/rtdip_sdk/pipelines/utilities/azure/adls_gen2_acl.py
Labels: bug, pipelines
