Repository rtdip/core, pull requests merged in 2024-08, with the labels that each got.

#794 Package version fixes
  setup.py
Labels: bug

#795 Update setup imports
  setup.py
Labels: bug

#797 Batch API Updates
  src/api/v1/batch.py
  tests/api/v1/api_test_objects.py
  tests/api/v1/test_api_batch.py
Labels: queries

#798 University Essentials Updates
  docs/university/essentials/rtdip/architecture/databricks.md
  docs/university/essentials/rtdip/architecture/pipelines.md
  docs/university/essentials/rtdip/architecture/queries.md
  docs/university/essentials/rtdip/assets/rtdip_databricks.png
  docs/university/essentials/rtdip/assets/rtdip_sdk_pipelines.png
  docs/university/essentials/rtdip/assets/rtdip_sdk_queries.png
  docs/university/essentials/rtdip/introduction/overview.md
  docs/university/essentials/rtdip/introduction/prerequisites.md
  docs/university/essentials/rtdip/overview.md
  docs/university/essentials/sdk/authentication/azure.md
  docs/university/essentials/sdk/authentication/databricks.md
  docs/university/essentials/sdk/authentication/exercise.md
  docs/university/essentials/sdk/connectors/databricks-sql-connector.md
  docs/university/essentials/sdk/connectors/exercise.md
  docs/university/essentials/sdk/connectors/odbc-connectors.md
  docs/university/essentials/sdk/connectors/spark-connector.md
  docs/university/essentials/sdk/getting-started/exercise.md
  docs/university/essentials/sdk/getting-started/installation.md
  docs/university/essentials/sdk/getting-started/introduction.md
  docs/university/essentials/sdk/getting-started/prerequisites.md
  docs/university/essentials/sdk/queries/exercise.md
  docs/university/essentials/sdk/queries/sql.md
  docs/university/essentials/sdk/queries/timeseries.md
  docs/university/essentials/sdk/queries/weather.md
  mkdocs.yml
Labels: documentation

#800 RTDIP University Course Design and API Content
  docs/api/authentication.md
  docs/api/overview.md
  docs/api/rest_apis.md
  docs/overrides/essentials.css
  docs/overrides/essentials.html
  docs/overrides/images/rtdip-queries.png
  docs/overrides/images/university-course-badge.png
  docs/overrides/images/university-essential-course.png
  docs/overrides/images/university-pipeline-course.png
  docs/overrides/university.css
  docs/overrides/university.html
  docs/university/essentials/api/assets/postman.png
  docs/university/essentials/api/authentication.md
  docs/university/essentials/api/exercise.md
  docs/university/essentials/api/overview.md
  docs/university/essentials/api/postman.md
  docs/university/essentials/api/swagger.md
  docs/university/essentials/excel-connector/overview.md
  docs/university/essentials/overview.md
  docs/university/essentials/rtdip/introduction/prerequisites.md
  docs/university/essentials/sdk/authentication/azure.md
  docs/university/essentials/sdk/authentication/databricks.md
  docs/university/essentials/sdk/connectors/databricks-sql-connector.md
  docs/university/essentials/sdk/connectors/exercise.md
  docs/university/essentials/sdk/connectors/odbc-connectors.md
  docs/university/essentials/sdk/connectors/spark-connector.md
  docs/university/essentials/sdk/getting-started/exercise.md
  docs/university/essentials/sdk/getting-started/installation.md
  docs/university/essentials/sdk/getting-started/introduction.md
  docs/university/essentials/sdk/getting-started/prerequisites.md
  docs/university/essentials/sdk/queries/exercise.md
  docs/university/essentials/sdk/queries/sql.md
  docs/university/essentials/sdk/queries/timeseries.md
  docs/university/essentials/sdk/queries/weather.md
  docs/university/overview.md
  mkdocs.yml
Labels: documentation

#805 University Course Content Updates
  docs/overrides/essentials.html
  docs/sdk/queries/functions.md
  docs/university/essentials/api/authentication.md
  docs/university/essentials/api/exercise.md
  docs/university/essentials/api/overview.md
  docs/university/essentials/api/postman.md
  docs/university/essentials/api/swagger.md
  docs/university/essentials/excel-connector/dashboard.md
  docs/university/essentials/excel-connector/functions.md
  docs/university/essentials/excel-connector/getting-started.md
  docs/university/essentials/excel-connector/overview.md
  docs/university/essentials/excel-connector/taskpane.md
  docs/university/essentials/powerbi/exercise.md
  docs/university/essentials/powerbi/overview.md
  docs/university/essentials/rtdip/architecture/databricks.md
  docs/university/essentials/rtdip/architecture/pipelines.md
  docs/university/essentials/rtdip/architecture/queries.md
  docs/university/essentials/rtdip/introduction/overview.md
  docs/university/essentials/rtdip/introduction/prerequisites.md
  docs/university/essentials/sdk/authentication/azure.md
  docs/university/essentials/sdk/authentication/databricks.md
  docs/university/essentials/sdk/authentication/overview.md
  docs/university/essentials/sdk/connectors/databricks-sql-connector.md
  docs/university/essentials/sdk/connectors/exercise.md
  docs/university/essentials/sdk/connectors/odbc-connectors.md
  docs/university/essentials/sdk/connectors/overview.md
  docs/university/essentials/sdk/connectors/spark-connector.md
  docs/university/essentials/sdk/getting-started/exercise.md
  docs/university/essentials/sdk/getting-started/installation.md
  docs/university/essentials/sdk/getting-started/introduction.md
  docs/university/essentials/sdk/getting-started/prerequisites.md
  docs/university/essentials/sdk/queries/exercise.md
  docs/university/essentials/sdk/queries/sql.md
  docs/university/essentials/sdk/queries/timeseries.md
  docs/university/essentials/sdk/queries/weather.md
Labels: documentation

#808 Batch API updates
  environment.yml
  src/api/v1/batch.py
  src/api/v1/common.py
  src/api/v1/models.py
Labels: queries

#810 v0.12.1
  docs/sdk/authentication/azure.md
  docs/university/essentials/api/exercise.md
  environment.yml
  src/api/v1/batch.py
  src/api/v1/common.py
  src/api/v1/models.py
Labels: release

#812 Query changes related to date_format, this will improve the performance of the queries.
  environment.yml
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
  tests/sdk/python/rtdip_sdk/queries/_test_utils/sdk_test_objects.py
  tests/sdk/python/rtdip_sdk/queries/time_series/test_interpolate.py
Labels: queries

#819 Fix Interpolation at Time Data Mismatch
  src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
  tests/sdk/python/rtdip_sdk/queries/_test_utils/sdk_test_objects.py
Labels: queries
